os:
  - linux
  - windows
  - osx
language: node_js
node_js:
  - "8"
  - "10"
addons:
  apt:
    packages:
      - xvfb
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export DISPLAY=':99.0' ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 & ; fi
